AWSTemplateFormatVersion: '2010-09-09'
Description: Check for required tags on resources
Resources:
  ConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: "required-tags"
      Description: "Checks if your resources have the tags that you specify. For example, you can check whether your Amazon EC2 instances have the `CostCenter` tag, while also checking if all your RDS instance have one set of Keys tag. Separate multiple values with comm.."
      Source:
        Owner: "AWS"
        SourceIdentifier: "REQUIRED_TAGS"
      Scope:
        ComplianceResourceTypes:
          - "AWS::ACM::Certificate"
          - "AWS::AutoScaling::AutoScalingGroup"
          - "AWS::CloudFormation::Stack"
          - "AWS::CodeBuild::Project"
          - "AWS::DynamoDB::Table"
          - "AWS::EC2::CustomerGateway"
          - "AWS::EC2::Instance"
          - "AWS::EC2::InternetGateway"
          - "AWS::EC2::NetworkAcl"
          - "AWS::EC2::NetworkInterface"
          - "AWS::EC2::RouteTable"
          - "AWS::EC2::SecurityGroup"
          - "AWS::EC2::Subnet"
          - "AWS::EC2::Volume"
          - "AWS::EC2::VPC"
          - "AWS::EC2::VPNConnection"
          - "AWS::EC2::VPNGateway"
          - "AWS::ElasticLoadBalancing::LoadBalancer"
          - "AWS::ElasticLoadBalancingV2::LoadBalancer"
          - "AWS::RDS::DBInstance"
          - "AWS::RDS::DBSecurityGroup"
          - "AWS::RDS::DBSnapshot"
          - "AWS::RDS::DBSubnetGroup"
          - "AWS::RDS::EventSubscription"
          - "AWS::Redshift::Cluster"
          - "AWS::Redshift::ClusterParameterGroup"
          - "AWS::Redshift::ClusterSecurityGroup"
          - "AWS::Redshift::ClusterSnapshot"
          - "AWS::Redshift::ClusterSubnetGroup"
          - "AWS::S3::Bucket"
      InputParameters:
        tag1Key: "CostCenter"
